bin/magento setup:install \
--base-url=http://magento2front.loc \
--db-host=localhost \
--db-name=magento2front \
--db-user=root \
--db-password=q1234e \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
